site_name: Unisinos PPGCA
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  logo:
    icon: cloud

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Learning: learning.md
  - Cluster Access: cluster_access.md
  - Minikube Setup: minikube_setup.md
  - Troubleshooting: troubleshooting.md